version: '3.7'

services:
  postgres:
    image: postgres:16.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tickdown
      POSTGRES_PASSWORD: "LOCAL_TEST_PASSWORD"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
